<MainScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Gestor de Notas"
            font_size: 24
        Button:
            text: "Registrar Usuario"
            on_press: root.registrar_usuario()
        Button:
            text: "Iniciar Sesión"
            on_press: root.iniciar_sesion()
        Button:
            text: "Salir"
            on_press: root.salir()
